# Generated by Django 6.0.4 on 2026-06-08 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0002_houseuser_alter_servicerequest_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuser',
            name='is_active',
            field=models.BooleanField(default=False),
        ),
    ]
