# Generated by Django 6.0.6 on 2026-06-13 04:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('SMSApp', '0003_houseuser_is_active'),
    ]

    operations = [
        migrations.AddField(
            model_name='houseuser',
            name='reset_token',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
